version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hospital-frontend
    ports:
      - "80:80"
    networks:
      - distribuidas-net

networks:
  distribuidas-net:
    external: true 